# Generated by Django 4.0.2 on 2022-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('speaker', models.CharField(max_length=30)),
                ('event_data', models.DateTimeField()),
            ],
        ),
    ]
