# Generated by Django 4.0.3 on 2022-03-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('author_pic', models.ImageField(upload_to='images/')),
                ('blog_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50)),
                ('post_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.CharField(default='about', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/en/b/b0/IEEE_Communications_Society_Logo.png', upload_to='images/'),
        ),
    ]
