# Generated by Django 4.0.3 on 2022-04-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_posts_event_event_description_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=80)),
                ('regno', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
