# Generated by Django 4.0.3 on 2022-04-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reg',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
