# Generated by Django 4.0.3 on 2022-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_event_reg_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_reg',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
